### ISSUE TITLE
No flow when sending a low number of bytes using BulkSend app

### ISSUE THREAD

**Issue by abedaeed17** [signetlabdei/quic-ns-3#43] opened 2024-03-17 23:43 UTC
Hi,
I am trying to send a specific number of bytes over QUIC using the BulkSend app, but it seems like there is no traffic at all of I set the maximum amount of bytes to be lower than a specific threshold.
for example if I configure the MaxBytes attribute to 64KB (```bulkSendHelper.SetAttribute("MaxBytes", UintegerValue(64 * 1024));```), I see no traffic at all.
but if I configure it to 1MB for example (```bulkSendHelper.SetAttribute("MaxBytes", UintegerValue(1 * 1024 * 1024));```), then I can see traffic.

Is there any bug or limitation in the QUIC module? or am I missing something?

Thanks in advance.

**Comment by abedaeed17** [comment] 2024-03-17 23:45
Attaching the full relevant code, in case it is needed:
```
    // Create and configure a QUIC BulkSendApplication and install it on the QUIC server's node:
    Address remoteAddr(InetSocketAddress(ueIpIface.GetAddress(0), dlPort));
    BulkSendHelper bulkSendHelper("ns3::QuicSocketFactory", remoteAddr);
    bulkSendHelper.SetAttribute("MaxBytes", UintegerValue(calculatedFileSize));
    bulkSendHelper.SetAttribute("SendSize", UintegerValue(512));
    ApplicationContainer sourceApps = bulkSendHelper.Install(remoteHost);
    sourceApps.Start(Seconds(2));
    sourceApps.Stop(Seconds(simulationDuration));

    // Create and configure a QUIC PacketSinkApplication and install it on 'UE-0':
    PacketSinkHelper PacketSinkHelper("ns3::QuicSocketFactory", InetSocketAddress(Ipv4Address::GetAny(), dlPort));
    PacketSinkHelper.SetAttribute("Protocol", TypeIdValue(QuicSocketFactory::GetTypeId()));
    ApplicationContainer sinkApps = PacketSinkHelper.Install(ueNodes.Get(0));
    sinkApps.Start(Seconds(0));
    sinkApps.Stop(Seconds(simulationDuration));
```

**Comment by fedech** [comment] 2024-05-10 08:33
Sorry for the long delay, I've finally checked it out. The problem is that BulkSendApplication immediately closes the socket after it sends the data, so QUIC will not send pending data. If there are enough bytes not to open and close the connection immediately, it will work. This is expected behavior from the QUIC module, and you should avoid closing the socket in BulkSendApplication

**Closed as completed by fedech** 2024-05-10 08:33 UTC
